Задание 1
6ocra3/Golang_MK pull request #2
Opened 2024-03-31 11:32 UTC by 6ocra3

2024-03-31 11:33 UTC, 6ocra3 commented
@kirreal
@maxan98
@vbelogrudov

2024-03-31 13:16 UTC, vbelogrudov requested changes
лучше оформить стемминг-нормализацию отдельной функцией, чтобы можно было ее в будущем переиспользовать. Также эта функция (или метод) должна возвращать слайс, чтобы потом нам не разбивать слова снова. А main может сам склеить, как у тебя уже сделано, для fmt.Println

2024-03-31 13:16 UTC, vbelogrudov commented on myapp
лучше не класть бинарники в git, только в крайнем случае

2024-03-31 13:16 UTC, vbelogrudov commented on main.go
> +	sFlag := flag.String("s", "", "Флаг `-s` используется для ввода строки")
можно сделать чуть проще,
var input string
flag.StringVar(&string, "s", "", "....

2024-03-31 13:16 UTC, vbelogrudov commented on main.go
> +	if *sFlag != "" {
в го приветствуется минимум бренчей, обычно happy path по максимуму слева, error path - в if,

то есть:
if len(input) == 0 {
     print error
     return
}
happy path continues here

2024-03-31 13:16 UTC, vbelogrudov commented on main.go
> +	for _, token_code := range forbidden_tags {
можно сократить до
return slices.Contains(forbiddenTags, tok)

В го принят Pascal/camel case ;)

2024-03-31 13:16 UTC, vbelogrudov commented on main.go
> +				if _, ok := appended[stemmed]; !ok {
if appended[stemmed] {
    continue
}
по умолчанию при отсутствии ключа возвращается дефолтное значение типа, здесь - false

2024-03-31 13:17 UTC, vbelogrudov commented
выглядит уже хорошо, небольшие недочеты:

Golang_MK$ ./myapp -s 'follow, followers!'
follow , !

2024-03-31 21:43 UTC, 6ocra3 commented
Исправил все
@kirreal
@maxan98
@vbelogrudov

2024-04-01 07:06 UTC, vbelogrudov approved these changes
все в порядке, можно "дотьюнить" при необходимости в следующем задании

2024-04-21 14:42 UTC, merged