Неделя 2.
6ocra3/Golang_MK pull request #4
Opened 2024-04-03 21:38 UTC by 6ocra3

2024-04-03 22:01 UTC, 6ocra3 commented
Доброе утро, день, вечер!
Прошу посмотреть PR
@kirreal
@maxan98
@vbelogrudov

2024-04-05 09:24 UTC, vbelogrudov requested changes
необходимо понять, сколько нам скачивать комиксов всего, а также не скачивать те, которые уже есть в базе

2024-04-05 09:24 UTC, vbelogrudov commented on pkg/database/json.go
> +	"makar/stemmer/pkg/config"
database ничего не хочет знать о pkg/config, pkg/xkcd, только о расположении файла.
Можно здесь определить 
```
type Comics struct {
    ID  int `json:"-"`
    URL string `json:"url"`
    Keywords []string `json:"keywords`
}

type Database struct {
    Entries map[int]Comics
    FilePath string
}
```
и отдавать в requests Comics, заполняя на лету ID.

Database.Entries <-> database.json

2024-04-05 09:24 UTC, vbelogrudov commented on pkg/xkcd/client.go
> +type Comic struct {
эта структура принадлежит requests или database

2024-04-05 09:24 UTC, vbelogrudov commented on pkg/xkcd/client.go
> +var client = http.Client{}
в таком виде клиент бесполезен, можно просто использовать http.Get(). Но можно добавить в клиент timeout ;)

2024-04-05 09:24 UTC, vbelogrudov commented on pkg/xkcd/client.go
> +			return nil, err
если мы возвратимся, у нас могут зависнуть горутины, в которых нет ошибки. Можно попробовать errgroup https://pkg.go.dev/golang.org/x/sync/errgroup#example-Group-JustErrors

Тема распараллеливания у нас в следующем задании, поэтому здесь можно обойтись без горутин

2024-04-07 12:50 UTC, vbelogrudov requested changes
Golang_MK$ ./xkcd
Start fetching 1 50
Fetched: fatal error: all goroutines are asleep - deadlock!

2024-04-08 19:29 UTC, 6ocra3 commented
Обновил PR до дедлайна, прошу посмотреть, забыл тегнуть
@kirreal
@maxan98
@vbelogrudov

2024-04-21 14:42 UTC, merged