3-4 lesson
6ocra3/Golang_MK pull request #7
Opened 2024-04-21 14:42 UTC by 6ocra3

2024-04-21 14:43 UTC, 6ocra3 commented
PR с 3 и 4 уроком
@kirreal
@maxan98
@vbelogrudov

2024-04-22 10:34 UTC, vbelogrudov requested changes
привет,

в целом уже поиск работает,
хотелось бы еще получить вот этот комикс - https://xkcd.com/2496 


➜  6ocra3/Golang_MK git:(3_lesson) ✗ ./xkcd -i -s  "mines, captcha"                   

Комиксы обработаны
Комиксы сохранены
Индекс построен
Поиск по индекс файлу
https://imgs.xkcd.com/comics/suspicion.png
https://imgs.xkcd.com/comics/planet_killer_comet_margarita.png
https://imgs.xkcd.com/comics/a_softer_robot.jpg
https://imgs.xkcd.com/comics/juicer.png
https://imgs.xkcd.com/comics/words_for_pets.png
https://imgs.xkcd.com/comics/how_it_happened.png
https://imgs.xkcd.com/comics/moria.png
https://imgs.xkcd.com/comics/lunch.png
https://imgs.xkcd.com/comics/vacuum.png
https://imgs.xkcd.com/comics/hardware_reductionism.png

2024-04-27 14:05 UTC, vbelogrudov approved these changes

2024-04-27 14:05 UTC, vbelogrudov commented on cmd/xkcd/main_test.go
> +	b.ResetTimer()
после app := setup() , мы хотим померить поиск, а не построение базы

2024-05-11 12:01 UTC, merged